global:
  scrape_interval:     15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'job_name'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
